/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.Document;
import javax.swing.text.EditorKit;
import jsyntaxpane.DefaultSyntaxKit;
import jsyntaxpane.actions.CaretMonitor;
import jsyntaxpane.syntaxkits.JavaSyntaxKit;

/**
 *
 * @author Rum
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();

        EditorPannel.setEditorKit(new JavaSyntaxKit());
        DefaultSyntaxKit.initKit();

        EditorPannel.setContentType("text/java");
        SelezioneLing.setSelectedItem("text/java");
     
        new CaretMonitor(EditorPannel, IndiceRigaDoc);
        
        try {
            // Try to load a relatively big Java file
            loadFile("./target/generated-sources/jflex/jsyntaxpane/lexers/ClojureLexer.java");
        } catch (IOException ex) {
            // This happens when not building from source - ignore
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Toolbar = new javax.swing.JToolBar();
        LoadButton = new javax.swing.JButton();
        ChangeWorkspaceButton = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        ScrollTree = new javax.swing.JScrollPane();
        TreeNavigator = new javax.swing.JTree();
        EditorScroll = new javax.swing.JScrollPane();
        EditorPannel = new javax.swing.JEditorPane();
        IndiceRigaDoc = new javax.swing.JLabel();
        SelezioneLing = new javax.swing.JComboBox();
        SelLingLabel = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        SaveMenu = new javax.swing.JMenuItem();
        LoadFileMenu = new javax.swing.JMenuItem();
        ChangeWorkspaceMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Toolbar.setFloatable(false);

        LoadButton.setText("Load File");
        LoadButton.setFocusable(false);
        LoadButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoadButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });
        Toolbar.add(LoadButton);

        ChangeWorkspaceButton.setText("Change Workspace");
        ChangeWorkspaceButton.setFocusable(false);
        ChangeWorkspaceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ChangeWorkspaceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ChangeWorkspaceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeWorkspaceButtonMouseClicked(evt);
            }
        });
        ChangeWorkspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeWorkspaceButtonActionPerformed(evt);
            }
        });
        Toolbar.add(ChangeWorkspaceButton);

        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setDividerSize(10);

        TreeNavigator.setModel(new FileSystemModel(new File(workspace)));
        TreeNavigator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreeNavigatorMouseClicked(evt);
            }
        });
        ScrollTree.setViewportView(TreeNavigator);

        jSplitPane2.setLeftComponent(ScrollTree);

        EditorScroll.setViewportView(EditorPannel);

        jSplitPane2.setRightComponent(EditorScroll);

        IndiceRigaDoc.setText("Current Position");

        SelezioneLing.setModel(new DefaultComboBoxModel(DefaultSyntaxKit.getContentTypes()));
        SelezioneLing.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelezioneLingItemStateChanged(evt);
            }
        });

        SelLingLabel.setText("Select Lenguage: ");

        FileMenu.setText("File");

        SaveMenu.setText("Save File As");
        SaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuActionPerformed(evt);
            }
        });
        FileMenu.add(SaveMenu);

        LoadFileMenu.setText("Load File");
        LoadFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadFileMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LoadFileMenu);

        ChangeWorkspaceMenu.setText("Change Workspace");
        ChangeWorkspaceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeWorkspaceMenuActionPerformed(evt);
            }
        });
        FileMenu.add(ChangeWorkspaceMenu);

        MenuBar.add(FileMenu);

        jMenu4.setText("Edit");
        MenuBar.add(jMenu4);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SelLingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelezioneLing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 585, Short.MAX_VALUE)
                        .addComponent(IndiceRigaDoc))
                    .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelLingLabel)
                    .addComponent(SelezioneLing, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IndiceRigaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        
        final JFileChooser fc = new JFileChooser(workspace);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fc.getSelectedFile();
                path = file.getAbsolutePath();
                className = fc.getName(file);
                int i = path.lastIndexOf(".");
                classExtention = fc.getSelectedFile().getPath().substring(i+1);
                EditorPannel.setContentType("text/"+classExtention);
                SelezioneLing.setSelectedItem("text/"+classExtention);
     
                loadFile(fc.getSelectedFile().getPath());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_LoadButtonActionPerformed

    private void LoadFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadFileMenuActionPerformed
       
        final JFileChooser fc = new JFileChooser(workspace);
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                try {
                   
                    File file = fc.getSelectedFile();
                    path = file.getAbsolutePath();
                    className = fc.getName(file);
                    int i = fc.getSelectedFile().getPath().lastIndexOf(".");
                    classExtention = fc.getSelectedFile().getPath().substring(i+1);
                    EditorPannel.setContentType("text/"+classExtention);
                    SelezioneLing.setSelectedItem("text/"+classExtention);
     
                    loadFile(fc.getSelectedFile().getPath());
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
        }
    }//GEN-LAST:event_LoadFileMenuActionPerformed


    private void SelezioneLingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SelezioneLingItemStateChanged
       
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            
            String lang = SelezioneLing.getSelectedItem().toString();
            classExtention = lang.substring(5);
        
            if("python".equals(classExtention)) 
                classExtention = "py";
            
            
            System.out.println(classExtention);
            // save the state of the current JEditorPane, as it's Document is about
            // to be replaced.
            String oldText = EditorPannel.getText();

            // install a new DefaultSyntaxKit on the JEditorPane for the requested language.
            
            EditorPannel.setContentType(lang);
            
            // Recreate the Toolbar
            Toolbar.removeAll();
            EditorKit kit = EditorPannel.getEditorKit();
            
            if (kit instanceof DefaultSyntaxKit) {
                DefaultSyntaxKit defaultSyntaxKit = (DefaultSyntaxKit) kit;
                defaultSyntaxKit.addToolBarActions(EditorPannel, Toolbar);
            }
            Toolbar.add(LoadButton);
            Toolbar.add(ChangeWorkspaceButton);
            Toolbar.validate();
            try {
                // setText should not be called (read the JavaDocs).  Better use the read
                // method and create a new document:
                // jEdtTest.read(new StringReader(oldText), lang);

                // ... however, the default read() will trigger a call to insertString() for each line
                // of the document which again will a call to parse(), making the UI freeze for large documents.
                // Therefore, for large texts, its best to create a new document and insert the data in
                // a single operation:
                Document doc = kit.createDefaultDocument();
                doc.insertString(0, oldText, null);
                EditorPannel.setDocument(doc);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        EditorPannel.requestFocusInWindow();

        // TODO add your handling code here:
    }//GEN-LAST:event_SelezioneLingItemStateChanged

    private void TreeNavigatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreeNavigatorMouseClicked
        
        
        path = TreeNavigator.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "/");
   
        if(path.contains(".")){
            
            String result[] = path.split("/");
            String returnValue = result[result.length - 1];
            int i = returnValue.lastIndexOf(".");
            int j = path.lastIndexOf("/");
            path = path.substring(0, j);
            System.out.println(path);
            classExtention = returnValue.substring(i+1);
            SelezioneLing.setSelectedItem(ABORT);
            className = returnValue.substring(0, i);
            EditorPannel.setContentType("text/"+classExtention);
            SelezioneLing.setSelectedItem("text/"+classExtention);
     
            
            try {

                loadFile(TreeNavigator.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\"));

            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_TreeNavigatorMouseClicked

    private void SaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuActionPerformed
       
        JFileChooser fc;
        if(path == null){
           fc = new JFileChooser(workspace);
           fc.setSelectedFile(new File(workspace+"\\"+className+"."+classExtention));
        }
        else{
            
            fc = new JFileChooser(path);
            fc.setSelectedFile(new File(path+"\\"+className+"."+classExtention));
        }
      
         int returnVal = fc.showSaveDialog(Frame.this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fc.getSelectedFile();
                FileWriter out = new FileWriter(new File(fc.getCurrentDirectory(), className+"."+classExtention));
                out.write(EditorPannel.getText());
                out.close();
           } catch (IOException ex) {
               ex.printStackTrace();
           } 
        }
    }//GEN-LAST:event_SaveMenuActionPerformed

    private void ChangeWorkspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeWorkspaceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeWorkspaceButtonActionPerformed

    private void ChangeWorkspaceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeWorkspaceButtonMouseClicked
         final JFileChooser fc = new JFileChooser(workspace);
         fc.setFileSelectionMode(1);
         int returnVal = fc.showOpenDialog(this);
         if (returnVal == JFileChooser.APPROVE_OPTION) {                    
             workspace = fc.getSelectedFile().getAbsolutePath();
             TreeNavigator.setModel(new FileSystemModel(new File(workspace)));
             System.out.println(workspace);
        }
    }//GEN-LAST:event_ChangeWorkspaceButtonMouseClicked

    private void ChangeWorkspaceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeWorkspaceMenuActionPerformed
        final JFileChooser fc = new JFileChooser(workspace);
        fc.setFileSelectionMode(1);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {                    
            workspace = fc.getSelectedFile().getAbsolutePath();
            TreeNavigator.setModel(new FileSystemModel(new File(workspace)));
            System.out.println(workspace);
        }
    }//GEN-LAST:event_ChangeWorkspaceMenuActionPerformed

    private void loadFile(String filename) throws IOException {
        // This will load a file:
        EditorPannel.read(new FileInputStream(filename), null);

        // ... however, the default read() will trigger a call to insertString() for each line
        // of the document which again will a call to parse(), making the UI freeze for large files.
        // Therefore, for large texts, its best to create a new document and insert the data in
        // a single operation:
        /*Document doc = EditorPannel.getEditorKit().createDefaultDocument();
        String str = new String(Files.readAllBytes(Paths.get(filename)));
        try {
            doc.insertString(0, str, null);
        } catch (BadLocationException ex) {
            throw new IOException(ex); // Should never happen
        }
        EditorPannel.setDocument(doc);*/
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    private String workspace = "C:\\Users\\Rum\\workspace\\INGSW";
    private String className;
    private String path;
    private String classExtention = "java";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeWorkspaceButton;
    private javax.swing.JMenuItem ChangeWorkspaceMenu;
    private javax.swing.JEditorPane EditorPannel;
    private javax.swing.JScrollPane EditorScroll;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel IndiceRigaDoc;
    private javax.swing.JButton LoadButton;
    private javax.swing.JMenuItem LoadFileMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem SaveMenu;
    private javax.swing.JScrollPane ScrollTree;
    private javax.swing.JLabel SelLingLabel;
    private javax.swing.JComboBox<String> SelezioneLing;
    private javax.swing.JToolBar Toolbar;
    private javax.swing.JTree TreeNavigator;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
